name: Build VieSchedGUI macOS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          
      - name: Install Official Qt6 (Universal)
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.1'
          modules: 'qtcharts qtmultimedia qtwebengine'
          cache: true
          host: 'mac'
          target: 'desktop'
        
      - name: Debug Qt Path
        run: |
          echo "Qt dir: $Qt6_DIR"
          which qmake
          qmake -query

      - name: Install OpenMP
        run: brew install libomp

      - name: Install Boost
        run: brew install boost
        
#      - name: Install tools
#        run: |
#          brew install cmake git

      - name: Clone VieSchedpp core
        run: |
          git clone https://github.com/sozyildirim/VieSchedpp.git ../VieSchedpp

      - name: Configure project
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_PREFIX_PATH=$Qt6_DIR

      - name: Show repository structure
        run: |
          pwd
          ls -R
          
      - name: Build project
        run: |
          cd build
          make -j$(sysctl -n hw.ncpu)



      - name: Bundle Boost libraries
        run: |
          APP=build/VieSchedppGUI.app
          mkdir -p $APP/Contents/Frameworks

          BOOST_LIB=$(brew --prefix boost)/lib

          cp $BOOST_LIB/libboost*.dylib $APP/Contents/Frameworks/ || true

#      - name: Fix rpath
#        run: |
#          BINARY=build/VieSchedppGUI.app/Contents/MacOS/VieSchedppGUI
#          install_name_tool -add_rpath "@executable_path/../Frameworks" "$BINARY" || true
#

      - name: Deploy Qt libraries
        run: |
          cd build
          #macdeployqt VieSchedpp.app -verbose=1
          macdeployqt VieSchedppGUI.app -verbose=3 -dmg

      - name: Code sign app
        run: |
          codesign --force --deep --sign - build/VieSchedppGUI.app

      - name: Package app
        run: |
          cd build
          zip -r VieSchedppGUI-macos.zip VieSchedppGUI.app

    
      - name: Upload compiled app
        uses: actions/upload-artifact@v4
        with:
          name: VieSched-macos
          path: build/VieSchedppGUI-macos.zip

      - name: Check dependencies
        run: |
          ls -R build/VieSchedppGUI.app/Contents/Frameworks
          otool -L build/VieSchedppGUI.app/Contents/MacOS/VieSchedpp
          
      - name: Smoke test
        run: |
          ./build/VieSchedppGUI.app/Contents/MacOS/VieSchedppGUI --version
